// Словарь с русскими переводами названий колонок
const Map<String, String> columnTranslations = {
  'id': 'ID',
  'operation_quantity': 'Количество операций',
  'srid': 'ID заказа',
  'shk_id': 'Штрихкод',
  'sticker_id': 'Стикер',
  'rrd_id': 'Строка',
  'assembly_id': 'Задание',
  'nm_id': 'Артикул WB',
  'sa_name': 'Мой артикул',
  'barcode': 'Баркод',
  'gi_id': 'Номер поставки',
  'ppvz_office_id': 'Офис доставки',
  'order_uid': 'ID транзакции',
  'trbx_id': 'Номер короба',
  'seller_promo_id': 'ID акции продавца',
  'loyalty_id': 'ID скидки лояльности',
  'uuid_promocode': 'ID промокода',
  'subject_name': 'Предмет',
  'brand_name': 'Бренд',
  'ts_name': 'Размер',
  'doc_type_name': 'Тип документа',
  'supplier_oper_name': 'Обоснование',
  'bonus_type_name': 'Виды логистики, штрафов и корректировок ВВ',
  'payment_processing': 'Тип платежа за Эквайринг',
  'rr_dt': 'Дата операции',
  'order_dt': 'Дата заказа',
  'sale_dt': 'Дата продажи',
  'delivery_time_hours': 'Время доставки (в часах)',
  'type_fb': 'Тип FBO/FBS',
  'delivery_method': 'Способ продажи и тип товара',
  'gi_box_type_name': 'Тип коробов',
  'site_country': 'Страна продажи',
  'office_name': 'Склад',
  'ppvz_office_name': 'Наименование офиса доставки',
  'dlv_prc': 'Фиксированный коэффициент склада по поставке',
  'acquiring_percent': 'Размер комиссии за Эквайринг + Комиссии за организацию платежей, %',
  'commission_percent': 'Размер кВВ, %',
  'base_comission': 'Базовая комиссия',
  'penalty_commission_percent': 'Штрафная комиссия, %',
  'is_kgvp_v2': 'Размер снижения кВВ из-за акции, %',
  'loyalty_discount': 'Размер скидки лояльности от продавца, %',
  'ppvz_kvw_prc': 'Итоговый кВВ без НДС, %',
  'ppvz_kvw_prc_base': 'Размер кВВ без НДС, % базовый',
  'ppvz_spp_prc': 'Скидка постоянного Покупателя (СПП), %',
  'product_discount_for_report': 'Итоговая согласованная скидка, %',
  'sale_percent': 'Согласованный продуктовый дисконт, %',
  'sale_price_promocode_discount_prc': 'Скидка за промокод, %',
  'seller_promo_discount': 'Размер дополнительной скидки по собственной акции продавца, %',
  'sup_rating_prc_up': 'Размер снижения кВВ из-за рейтинга, %',
  'supplier_promo': 'Промокод, %',
  'wibes_wb_discount_percent': 'Скидка Wibes, %',
  'quantity': 'Количество',
  'delivery_amount': 'Количество доставок',
  'return_amount': 'Количество возврата',
  'retail_price': 'Цена розничная',
  'retail_amount': 'Вайлдберриз реализовал Товар (Пр)',
  'ppvz_for_pay': 'К перечислению продавцу за реализованный товар',
  'cost_price': 'Себестоимость',
  'additional_expenses': 'Доп.расходы',
  'commission_amount': 'Комиссия, руб.',
  'commission_normal': 'Нормальная комиссия',
  'penalty_commission_rub': 'Поздняя отгрузка',
  'delivery_rub': 'Логистика',
  'ppvz_reward': 'Возмещение за выдачу и возврат товаров на ПВЗ',
  'acquiring_fee': 'Эквайринг',
  'acceptance': 'Приемка',
  'cashback_amount': 'Сумма, удержанная за начисленные баллы программы лояльности',
  'cashback_commission_change': 'Стоимость участия в программе лояльности',
  'storage_fee': 'Хранение',
  'penalty': 'Штрафы',
  'deduction': 'Удержания',
  'installment_cofinancing_amount': 'Скидка по программе софинансирования',
  'additional_payment': 'Корректировка Вознаграждения Вайлдберриз (ВВ)',
  'payment_schedule': 'Разовое изменение срока перечисления денежных средств',
  'report_date': 'Дата отчета',
  // Возвраты
  'retail_price_recovery': 'Цена возврата',
  'retail_amount_refunded': 'Вайлдберриз принял возврат товара',
  'ppvz_for_recovery': 'К снятию с продавца за возвращенный товар',
  'cost_price_recovered': 'Возврат себестоимости',
  'additional_expenses_recovered': 'Возврат доп.расходов',
  'commission_amount_reversed': 'Отмененная комиссия',
  'commission_normal_reversed': 'Отмененная нормальная комиссия',
  'penalty_commission_reversed': 'Отмена корректировки комиссии',
  'return_delivery_rub': 'Стоимость обратной логистики',
  'ppvz_reward_reversed': 'Возврат удержания за ПВЗ',
  'acquiring_fee_reversed': 'Возврат эквайринга',
  'cashback_amount_reversed': 'Отмена удержания за начисленные баллы',
  'cashback_commission_change_reversed': 'Отмена удержания за участие в программе лояльности',
  'created_at': 'Дата создания',
  'updated_at': 'Дата обновления',
  'total': 'Итого',
};

// Словарь для отображения типа данных столбца (короткая метка)
const Map<String, String> columnTypeLabels = {
  'id': 'ID',
  'operation_quantity': '123',
  'srid': 'ID',
  'shk_id': 'ID',
  'sticker_id': 'ID',
  'rrd_id': 'ID',
  'assembly_id': 'ID',
  'nm_id': 'ID',
  'sa_name': 'ID',
  'barcode': 'ID',
  'gi_id': 'ID',
  'ppvz_office_id': 'ID',
  'order_uid': 'ID',
  'trbx_id': 'ID',
  'seller_promo_id': 'ID',
  'loyalty_id': 'ID',
  'uuid_promocode': 'ID',
  'subject_name': 'ID',
  'brand_name': 'ID',
  'ts_name': 'ID',
  'doc_type_name': 'ID',
  'supplier_oper_name': 'ID',
  'bonus_type_name': 'ID',
  'payment_processing': 'ID',
  'rr_dt': 'ДАТА',
  'order_dt': 'ДАТА',
  'sale_dt': 'ДАТА',
  'delivery_time_hours': 'ВРЕМЯ',
  'type_fb': 'ТИП',
  'delivery_method': 'ТИП',
  'gi_box_type_name': 'ТИП',
  'site_country': 'ID',
  'office_name': 'ID',
  'ppvz_office_name': 'ID',
  'dlv_prc': '123',
  'acquiring_percent': '%',
  'commission_percent': '%',
  'base_comission': '%',
  'penalty_commission_percent': '%',
  'is_kgvp_v2': '%',
  'loyalty_discount': '%',
  'ppvz_kvw_prc': '%',
  'ppvz_kvw_prc_base': '%',
  'ppvz_spp_prc': '%',
  'product_discount_for_report': '%',
  'sale_percent': '%',
  'sale_price_promocode_discount_prc': '%',
  'seller_promo_discount': '%',
  'sup_rating_prc_up': '%',
  'supplier_promo': '%',
  'wibes_wb_discount_percent': '%',
  'quantity': '123',
  'delivery_amount': '123',
  'return_amount': '123',
  'retail_price': '₽',
  'retail_amount': '₽',
  'ppvz_for_pay': '₽',
  'cost_price': '₽',
  'additional_expenses': '₽',
  'commission_amount': '₽',
  'commission_normal': '₽',
  'penalty_commission_rub': '₽',
  'delivery_rub': '₽',
  'ppvz_reward': '₽',
  'acquiring_fee': '₽',
  'acceptance': '₽',
  'cashback_amount': '₽',
  'cashback_commission_change': '₽',
  'storage_fee': '₽',
  'penalty': '₽',
  'deduction': '₽',
  'installment_cofinancing_amount': '₽',
  'additional_payment': '₽',
  'payment_schedule': '₽',
  'report_date': 'ДАТА',
  'retail_price_recovery': '₽',
  'retail_amount_refunded': '₽',
  'ppvz_for_recovery': '₽',
  'cost_price_recovered': '₽',
  'additional_expenses_recovered': '₽',
  'commission_amount_reversed': '₽',
  'commission_normal_reversed': '₽',
  'penalty_commission_reversed': '₽',
  'return_delivery_rub': '₽',
  'ppvz_reward_reversed': '₽',
  'acquiring_fee_reversed': '₽',
  'cashback_amount_reversed': '₽',
  'cashback_commission_change_reversed': '₽',
  'created_at': 'ДАТА',
  'updated_at': 'ДАТА',
  'total': 'УДАЛИТЬ',
};

// Список полей для вычисления итого
const List<String> totalFields = [
  'retail_price',
  'retail_price_recovery',
  'retail_amount',
  'retail_amount_refunded',
  'ppvz_for_pay',
  'ppvz_for_recovery',
  'cost_price',
  'cost_price_recovered',
  'additional_expenses',
  'additional_expenses_recovered',
  'commission_amount',
  'commission_amount_reversed',
  'commission_normal',
  'commission_normal_reversed',
  'penalty_commission_rub',
  'penalty_commission_reversed',
  'delivery_rub',
  'return_delivery_rub',
  'ppvz_reward',
  'ppvz_reward_reversed',
  'acquiring_fee',
  'acquiring_fee_reversed',
  'acceptance',
  'cashback_amount',
  'cashback_amount_reversed',
  'cashback_commission_change',
  'cashback_commission_change_reversed',
  'storage_fee',
  'penalty',
  'deduction',
  'additional_payment',
  'payment_schedule',
];

// Методы агрегации
const Map<String, String> aggregationMethods = {
  'none': 'Не агрегировать (пусто)',
  'count_unique': 'Количество уникальных значений',
  'concat': 'Конкатенация через запятую',
  'first_non_empty': 'Первое непустое значение',
  'sum': 'Сумма',
  'mean_with_null': 'Среднее (с учетом пустых)',
  'mean_without_null': 'Среднее (без учета пустых)',
  'max': 'Максимальное значение',
  'min': 'Минимальное значение',
};

// Доступные колонки с датами
const List<String> dateColumns = [
  'rr_dt',
  'order_dt',
  'sale_dt',
  'report_date',
  'created_at',
  'updated_at',
];

// Цвета для линий графика
const List<Color> chartColors = [
  Colors.red,
  Colors.orange,
  Colors.yellow,
  Colors.green,
  Colors.blue,
  Colors.purple,
  Colors.pink,
  Colors.black,
  Colors.brown,
];