from .db import db
from datetime import datetime

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nmID = db.Column(db.Integer, unique=True, nullable=False)
    imtID = db.Column(db.BigInteger)
    nmUUID = db.Column(db.String(36))
    subjectID = db.Column(db.Integer)
    subjectName = db.Column(db.String(200))
    vendorCode = db.Column(db.String(100))
    brand = db.Column(db.String(100))
    title = db.Column(db.Text)
    description = db.Column(db.Text)
    needKiz = db.Column(db.Boolean, default=False)
    photos = db.Column(db.Text)
    video = db.Column(db.String(500))
    wholesale_enabled = db.Column(db.Boolean, default=False)
    wholesale_quantum = db.Column(db.Integer)
    dimensions_length = db.Column(db.Integer)
    dimensions_width = db.Column(db.Integer)
    dimensions_height = db.Column(db.Integer)
    dimensions_weightBrutto = db.Column(db.Float)
    dimensions_isValid = db.Column(db.Boolean)
    characteristics = db.Column(db.Text)
    sizes = db.Column(db.Text)
    tags = db.Column(db.Text)
    created_at = db.Column(db.DateTime)
    updated_at = db.Column(db.DateTime)
    barcode = db.Column(db.String(30))